[build]
  command   = "npm install"
  functions = "netlify/functions"
  publish   = "."

[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to   = "/thank-you.html"
  status = 200
